env:
  browser: true
  es2020: true
extends:
  - airbnb
  - prettier
  - airbnb/hooks
  - plugin:prettier/recommended
  - plugin:react/recommended
  - prettier/@typescript-eslint
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - react-hooks
  - import
  - prettier
  - '@typescript-eslint/eslint-plugin'
rules:
  react/jsx-filename-extension: off
  '@typescript-eslint/explicit-module-boundary-types': off
  jsx-a11y/anchor-is-valid: warn
  prettier/prettier: ["error", { "singleQuote": true, "trailingComma": "all" }]
  import/extensions: off
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/no-autofocus: off
  '@typescript-eslint/ban-ts-comment': off
settings:
  import/resolver:
    node:
      paths: [components, lib, pages]
      extensions: [".js", ".jsx", ".ts", ".tsx"]
