# inspired from https://www.codegigs.app/how-to-cognito-user-pool-using-serverless/
service: api
provider:
  name: aws
  stage: ${opt:stage, 'stage'}
  region: ap-southeast-1
  runtime: nodejs12.x
  vpc: ${file(../layers/database/aliases.yml):database_vpc.${self:provider.stage}}

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 2727

functions:
  health:
    handler: functions/health.handler
    events:
      - http:
          path: health
          method: GET
  testDb:
    handler: functions/testDb.handler
    layers:
      - ${cf:layers-${self:provider.stage}.DatabaseLayerExport}
    events:
      - http:
          path: testDb
          method: GET

resources:
  Resources:
    MainPostgresDb:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: main
        DBInstanceIdentifier: main
        DBInstanceClass: db.t2.micro
        AllocatedStorage: 20
        Engine: postgres
        EngineVersion: 12.3
        MasterUsername: ${env:MAIN_DATABASE_USERNAME}
        MasterUserPassword: ${env:MAIN_DATABASE_PASSWORD}

    AWSLambdaVPCAccessExecutionRole: # from https://medium.com/@antonio.cm.oliveira/how-to-access-your-rds-database-with-lambda-function-and-serverless-b7712dde9f80
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - !Ref IamRoleLambdaExecution
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"
  Outputs:
    MainPostgresInstanceId:
      Description: InstanceId of the newly created RDS Instance
      Value: !Ref MainPostgresDb
