# inspired from https://www.codegigs.app/how-to-cognito-user-pool-using-serverless/
service: api
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  stage: ${opt:stage, 'stage'}
  region: ap-southeast-1
  runtime: nodejs12.x

functions:
  health:
    handler: functions/health.default
    events:
      - http:
          path: health
          method: GET

resources:
  Resources:
    MainPostgresDb:
      Type: AWS::RDS::DBInstance
      Properties:
        DBName: main
        DBInstanceIdentifier: main
        DBInstanceClass: db.t2.micro
        AllocatedStorage: 20
        Engine: postgres
        EngineVersion: 12.3
        MasterUsername: ${env:MAIN_DATABASE_USERNAME}
        MasterUserPassword: ${env:MAIN_DATABASE_PASSWORD}
  Outputs:
    MainPostgresInstanceId:
      Description: InstanceId of the newly created RDS Instance
      Value: !Ref MainPostgresDb
