# inspired from https://www.codegigs.app/how-to-cognito-user-pool-using-serverless/
service: api
plugins:
  - serverless-webpack

provider:
  name: aws
  stage: ${opt:stage, 'stage'}
  region: ap-southeast-1
  runtime: nodejs12.x

functions:
  health:
    handler: functions/health.default
    events:
      - http:
          path: health
          method: GET
